import { StarFilledIcon } from "@radix-ui/react-icons"
import Image from "next/image";

const HeroMobile = () => {
    return (
        <section className='md:hidden w-full h-auto pt-20 px-5'>
            <div className=" flex flex-col items-center justify-center">
                <h1 className="text-center font-bold text-4xl bg-gradient-to-r from-[#F22E76] to-[#5D14A6] text-transparent bg-clip-text">
                    Add Subtitles to Video
                </h1>
                <div className="flex gap-2 py-3">
                    {[...Array(5)].map((_, index) => {
                        return (
                            <StarFilledIcon key={index} color="#E6B300" width={30} height={30} />
                        );
                    })}
                </div>
                <p className="text-center text-black">
                    Add captions and subtitles to your video.
                    Automatic, Fast <span className="text-white rounded-sm bg-purple-500 p-1 whitespace-nowrap">In Just One Click</span>
                </p>
            </div>
            <div className="mx-5 flex flex-col items-center justify-center">
                <Image
                    className="py-7"
                    src={"./landing-page-assets/subShort.svg"}
                    width={300}
                    height={50}
                    alt="short video image"
                />
                <button className="rounded-full px-5 py-3 text-white bg-[#F22E76]">Create my video now</button>
            </div>
            <div className="flex flex-col justify-center items-center py-7">
                <h1 className="text-center font-bold text-2xl text-black pb-3">
                    Fast And Effortless
                    Captions <span className="bg-gradient-to-r from-[#F22E76] to-[#5D14A6] text-transparent bg-clip-text">Powerd By AI</span>
                </h1>
                <p className="text-[#646464] text-center">
                    Effortless Captions with perfect emojis and intelligently highlighted keywords, all generated by AI.
                </p>
            </div>
        </section>
    )
}

export default HeroMobile
