import Image from "next/image";
import { StarFilledIcon } from "@radix-ui/react-icons"

const Hero = () => {
    return (
        <section className="max-md:hidden w-full h-auto pt-20 px-5">
            <div className="flex justify-center items-center">
                <Image
                    className="py-7"
                    src={"./landing-page-assets/short.svg"}
                    width={240}
                    height={50}
                    alt="short video image"
                />
                <div className="w-75 flex flex-col justify-center items-center px-3">
                    <div>
                        <h1 className="text-center font-bold text-3xl bg-gradient-to-r from-[#F22E76] to-[#5D14A6] text-transparent bg-clip-text">
                            Add Subtitles to Video
                        </h1>
                        <div className="flex gap-2 py-1 items-center justify-center">
                            {[...Array(5)].map((_, index) => {
                                return (
                                    <StarFilledIcon key={index} color="#E6B300" width={30} height={30} />
                                );
                            })}
                        </div>
                        <p className="text-center text-black">
                            Add captions and subtitles to your video.
                            Automatic, Fast <span className="text-white rounded-sm bg-purple-500 p-1 whitespace-nowrap">In Just One Click</span>
                        </p>
                    </div>
                    <Image
                        className="my-10"
                        src={'./landing-page-assets/arrow.svg'}
                        width={210}
                        height={10}
                        alt="arrow"
                    />
                    <button className="rounded-full px-5 py-3 text-white bg-[#F22E76]">Create my video now</button>
                </div>
                <Image
                    className="py-7"
                    src={"./landing-page-assets/subShort.svg"}
                    width={240}
                    height={50}
                    alt="short video image"
                />
            </div>
            <div className="py-7">
                <h1 className="text-center font-bold text-5xl text-black pb-3">
                    Fast And Effortless
                    Captions <span className="bg-gradient-to-r from-[#F22E76] to-[#5D14A6] text-transparent bg-clip-text">Powerd By AI</span>
                </h1>
                <p className="text-[#646464] text-center">
                    Effortless Captions with perfect emojis and intelligently highlighted keywords, all generated by AI.
                </p>
            </div>
        </section>
    );

}

export default Hero
